# Jon Bryan Ortiz, s1234567 - Operating Systems Project 1
# ca216/myshell

myshell: myshell.c external.c internal.c commands.c myshell.h internal.h commands.h
	gcc -Wall myshell.c commands.c internal.c external.c -o myshell
